coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
    patch:
      default:
        target: 90%

comment:
  layout: 'condensed_header, diff, flags'
  behavior: default

ignore:
  - 'apps/**'
  - '**/*.config.ts'
  - '**/*.spec.ts'
