packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@swc/core': true
  cpu-features: false
  esbuild: true
  prisma: true
  protobufjs: false
  yarn: false
  ssh2: false
